language: php

php:
  - 5.5
  - 5.6

env:
  - DB=mysql

before_script:
  - mv travis.env.php .env.testing.php
  - mysql -e 'create database IF NOT EXISTS defdx;'
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev
  - chmod -R 777 app/storage
  - php artisan migrate:install --env=testing --no-interaction -vvv

script:
 - php artisan migrate --env=testing --no-interaction -vvv
 - php artisan db:seed --env=testing --no-interaction -vvv
 - vendor/bin/codecept run
 - php artisan migrate:rollback --env=testing --no-interaction -vvv

matrix:
  fast_finish: true